### ISSUE TITLE
postinstall error

### ISSUE THREAD

**Issue by a-x-** [electron/electron-api-demos#244]
os x, node v6.3.0 (via nvm)

tail of npm i
```
> electron-prebuilt@1.2.6 postinstall /Users/invntrm/Projects/Xp/electron-quick-start/node_modules/electron-prebuilt
> node install.js

undefined:1
{=true
 ^

SyntaxError: Unexpected token = in JSON at position 1
    at Object.parse (native)
    at exports.parse (/Users/invntrm/Projects/Xp/electron-quick-start/node_modules/rc/lib/utils.js:15:17)
    at addConfigFile (/Users/invntrm/Projects/Xp/electron-quick-start/node_modules/rc/index.js:31:20)
    at Array.forEach (native)
    at module.exports (/Users/invntrm/Projects/Xp/electron-quick-start/node_modules/rc/index.js:44:36)
    at Object.<anonymous> (/Users/invntrm/Projects/Xp/electron-quick-start/node_modules/electron-download/index.js:9:26)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

tail of npm-debug.log:
```
12971 verbose lifecycle electron-prebuilt@1.2.6~postinstall: PATH: /Users/invntrm/.nvm/versions/node/v6.3.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/invntrm/Projects/Xp/electron-quick-start/node_modules/electron-prebuilt/node_modules/.bin:/Users/invntrm/Projects/Xp/electron-quick-start/node_modules/.bin:/Users/invntrm/.nvm/versions/node/v6.3.0/bin:/Users/invntrm/.nvm/versions/node/v6.3.0/bin:/usr/local/share/npm/bin:/Users/invntrm/node_modules/.bin:../../node_modules/.bin:./node_modules/.bin:bin:.bin:/Users/invntrm/dotfiles/bin:/Users/invntrm/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/munki:/Users/invntrm/xp/ya:/Users/invntrm/tools/islands-ci-helpers/bin:/Users/invntrm/.bem-levels
12972 verbose lifecycle electron-prebuilt@1.2.6~postinstall: CWD: /Users/invntrm/Projects/Xp/electron-quick-start/node_modules/electron-prebuilt
12973 silly lifecycle electron-prebuilt@1.2.6~postinstall: Args: [ '-c', 'node install.js' ]
12974 silly lifecycle electron-prebuilt@1.2.6~postinstall: Returned: code: 1  signal: null
12975 info lifecycle electron-prebuilt@1.2.6~postinstall: Failed to exec postinstall script
12976 verbose unlock done using /Users/invntrm/.npm/_locks/staging-20dde8ff33fd5bdf.lock for /Users/invntrm/Projects/Xp/electron-quick-start/node_modules/.staging
12977 silly rollbackFailedOptional Starting
12978 silly rollbackFailedOptional Finishing
12979 silly runTopLevelLifecycles Starting
12980 silly runTopLevelLifecycles Finishing
12981 silly install printInstalled
12982 verbose stack Error: electron-prebuilt@1.2.6 postinstall: `node install.js`
12982 verbose stack Exit status 1
12982 verbose stack     at EventEmitter.<anonymous> (/Users/invntrm/.nvm/versions/node/v6.3.0/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
12982 verbose stack     at emitTwo (events.js:106:13)
12982 verbose stack     at EventEmitter.emit (events.js:191:7)
12982 verbose stack     at ChildProcess.<anonymous> (/Users/invntrm/.nvm/versions/node/v6.3.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
12982 verbose stack     at emitTwo (events.js:106:13)
12982 verbose stack     at ChildProcess.emit (events.js:191:7)
12982 verbose stack     at maybeClose (internal/child_process.js:852:16)
12982 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
12983 verbose pkgid electron-prebuilt@1.2.6
12984 verbose cwd /Users/invntrm/Projects/Xp/electron-quick-start
12985 error Darwin 15.5.0
12986 error argv "/Users/invntrm/.nvm/versions/node/v6.3.0/bin/node" "/Users/invntrm/.nvm/versions/node/v6.3.0/bin/npm" "i"
12987 error node v6.3.0
12988 error npm  v3.10.3
12989 error code ELIFECYCLE
12990 error electron-prebuilt@1.2.6 postinstall: `node install.js`
12990 error Exit status 1
12991 error Failed at the electron-prebuilt@1.2.6 postinstall script 'node install.js'.
12991 error Make sure you have the latest version of node.js and npm installed.
12991 error If you do, this is most likely a problem with the electron-prebuilt package,
12991 error not with npm itself.
12991 error Tell the author that this fails on your system:
12991 error     node install.js
12991 error You can get information on how to open an issue for this project with:
12991 error     npm bugs electron-prebuilt
12991 error Or if that isn't available, you can get their info via:
12991 error     npm owner ls electron-prebuilt
12991 error There is likely additional logging output above.
12992 verbose exit [ 1, true ]

```

**Comment by zeke** [comment]
I just did `rm -rf node_modules && npm i` using node 6.3.0 and didn't have any installation errors, but when I `npm start` I also see an error related to `electron-prebuilt`:

```
> ElectronAPIDemos@1.1.0 start /Users/zeke/electron/electron-api-demos
> electron .

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/zeke/electron/electron-api-demos/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/Users/zeke/electron/electron-api-demos/node_modules/electron-prebuilt/index.js:4:42)
...
```

**Comment by zeke** [comment]
Hmm. I did another fresh install and it's working fine. I am unable so far to deterministically reproduce a failure.

**Comment by jlord** [comment]
> `Error: ENOENT: no such file or directory, open '/Users/zeke/electron/electron-api-demos/node_modules/electron-prebuilt/path.txt'`

@zeke Yeah we've seen that error before and it's been an npm blip.

**Comment by jlord** [comment]
@a-x- have you had any better luck with this?

**Comment by jlord** [comment]
Closing this out as stale. Feel free to update the thread if you reinstall and things work.
