### ISSUE TITLE
electron app not running by electron .

### ISSUE THREAD

**Issue by vnsharma-systango** [electron/electron-api-demos#282]
I am working on windows 10
Initially i was able to run app but suddenly next day when i am runing my app using "electron ."  it is giving following error:-

C:\Users\admin\Downloads\New folder\new2\win_codesktop>electron .
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\admin\AppData\Roaming\npm\node_modules\electron\path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\electron\index.js:4:42)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by zeke** [comment]
What happens when you run `npm start`?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in https://github.com/electron/electron-api-demos/issues/282#issuecomment-268149873. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
