### ISSUE TITLE
unable to npm install for demo app

### ISSUE THREAD

**Issue by sonimitesh** [electron/electron-api-demos#317]
* What operating system are you using? OSX
* What version of Node.js is on your system? tried with 4, 6, 7
while - npm install
below is the error on console
--------
electron-quick-start iMitesh$ npm install
npm ERR! Unexpected end of input at 1:17249
npm ERR! "directories":{},"dist":{"shasum":"02f574bfc533ae4c18776014a5070dced4
npm ERR!                                                                      ^

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/iMitesh/.npm/_logs/2017-07-30T14_16_15_601Z-debug.log
-------- below is the log file generated - skipping 352 lines
353 silly resolveWithNewModule rimraf@2.6.1 checking installable status
354 http fetch GET 304 https://registry.npmjs.org/glob 164ms (from cache)
355 silly fetchPackageMetaData error for glob@^7.0.5 Unexpected end of input at 1:17249
355 silly fetchPackageMetaData "directories":{},"dist":{"shasum":"02f574bfc533ae4c18776014a5070dced4
355 silly fetchPackageMetaData                                                                      ^
356 verbose stack SyntaxError: Unexpected end of input at 1:17249
356 verbose stack "directories":{},"dist":{"shasum":"02f574bfc533ae4c18776014a5070dced4
356 verbose stack                                                                      ^
356 verbose stack     at SyntaxError (native)
356 verbose stack     at Object.parseJSON (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/node_modules/jju/lib/parse.js:745:13)
356 verbose stack     at parse (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/index.js:10:13)
356 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50
356 verbose stack     at process._tickCallback (node.js:438:9)
357 verbose cwd /Users/iMitesh/WebstormProjects/mph/electron-quick-start
358 verbose Darwin 16.5.0
359 verbose argv "/usr/local/Cellar/node@4/4.8.4_1/bin/node" "/usr/local/bin/npm" "install"
360 verbose node v4.8.4
361 verbose npm  v5.3.0
362 error Unexpected end of input at 1:17249
362 error "directories":{},"dist":{"shasum":"02f574bfc533ae4c18776014a5070dced4
362 error                                                                      ^
363 verbose exit [ 1, true ]

**Comment by sonimitesh** [comment]
issue resolved by following
npm cache clean --force 
Thanks - however, can anyone tell me what causes this issue?
