### ISSUE TITLE
problem with node install

### ISSUE THREAD

**Issue by nascarsayan** [electron/electron-api-demos#319]

**Comment by nascarsayan** [comment]
npm install gives error. i have uploaded the npm-debug.log. Any help is appreciated.
[npm-debug.txt](https://github.com/electron/electron-api-demos/files/1202904/npm-debug.txt)

**Comment by nascarsayan** [comment]
Problem with npm start. Can't figure out the reason. Any help is appreciated :-D
My log-file:

```0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ElectronAPIDemos@1.3.0~prestart: ElectronAPIDemos@1.3.0
6 silly lifecycle ElectronAPIDemos@1.3.0~prestart: no script for prestart, continuing
7 info lifecycle ElectronAPIDemos@1.3.0~start: ElectronAPIDemos@1.3.0
8 verbose lifecycle ElectronAPIDemos@1.3.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle ElectronAPIDemos@1.3.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/hindpos/electron-api-demos/node_modules/.bin:/home/hindpos/bin:/home/hindpos/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle ElectronAPIDemos@1.3.0~start: CWD: /home/hindpos/electron-api-demos
11 silly lifecycle ElectronAPIDemos@1.3.0~start: Args: [ '-c', 'electron .' ]
12 info lifecycle ElectronAPIDemos@1.3.0~start: Failed to exec start script
13 verbose stack Error: ElectronAPIDemos@1.3.0 start: `electron .`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:891:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid ElectronAPIDemos@1.3.0
15 verbose cwd /home/hindpos/electron-api-demos
16 error Linux 4.4.0-89-generic
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
18 error node v6.11.2
19 error npm  v3.10.10
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error ElectronAPIDemos@1.3.0 start: `electron .`
24 error spawn ENOENT
25 error Failed at the ElectronAPIDemos@1.3.0 start script 'electron .'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the ElectronAPIDemos package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     electron .
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs ElectronAPIDemos
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls ElectronAPIDemos
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]```

**Comment by yanqi321** [comment]
I met the same problem as you. Have you solved the problem？

**Comment by marlboro15005** [comment]
I’m able to read code

**Comment by d3z3l** [comment]
having same problem

**Comment by codebytere** [comment]
@nascarsayan as a first check, did you try updating Node to a more recent version? `v6.11.2` is rather old now.

**Comment by yanqi321** [comment]
thanks，The problem has been solved， try cnpm instead of change its registory, but i still unable to understand its principle
