### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by firebird42** [electron/electron-api-demos#321]
* What operating system are you using? Ubuntu 16.04.2 LTS 64-Bit
* What version of Node.js is on your system? v7.10.0
I'm getting an error when running ```npm start```, "electron ." fails
```
> electron-quick-start@1.0.0 start /home/paul/Personal/projects/electron-quick-start
> electron .

/home/paul/Personal/projects/electron-quick-start/node_modules/electron/index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (/home/paul/Personal/projects/electron-quick-start/node_modules/electron/index.js:9:9)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/paul/Personal/projects/electron-quick-start/node_modules/electron/cli.js:3:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm ERR! Linux 4.4.0-81-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/paul/Personal/projects/electron-quick-start/npm-debug.log
```

[npm-debug.txt](https://github.com/electron/electron-api-demos/files/1257163/npm-debug.txt)

**Comment by C-Merrill** [comment]
I'm pretty new to this software as well, but it looks like your machine is building with node v4.2.6. I'm pretty sure that version is too old to properly build electron, so try deleting relevant node_modules, check/upgrade your global node version, and try again.
