### ISSUE TITLE
can't install and run electron

### ISSUE THREAD

**Issue by MAinulYaqin** [electron/electron-api-demos#339]
* What operating system are you using? 
Ubuntu 17.04
* What version of Node.js is on your system?
node v8.9.1 and npm 5.5.1

when installing, it stuck at :

```
> electron@1.6.15 postinstall /home/ainul/Desktop/electron-api-demos/node_modules/electron
> node install.js
```
when i run ```electron .```
i getting this error :

```
> ElectronAPIDemos@1.3.0 start /home/ainul/Desktop/electron-api-demos
> electron .

/home/ainul/Desktop/electron-api-demos/node_modules/electron/index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (/home/ainul/Desktop/electron-api-demos/node_modules/electron/index.js:9:9)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ainul/Desktop/electron-api-demos/node_modules/electron/cli.js:3:16)
    at Module._compile (module.js:635:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ElectronAPIDemos@1.3.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ElectronAPIDemos@1.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ainul/.npm/_logs/2018-01-22T01_59_58_851Z-debug.log
```

**Comment by shiftkey** [comment]
```
Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
```

Can you try removing `node_modules` and attaching the result of `npm install`? Maybe some dependency is missing that Electron requires.

**Comment by MAinulYaqin** [comment]
ok. wait

**Comment by MAinulYaqin** [comment]
it's work :+1:   thanks sir, you saved me

there is written to delete ```node_modules/electron``` so i assume to delete electron folder inside of node_modules. -_-
