### ISSUE TITLE
path is not defined during load (macos)

### ISSUE THREAD

**Issue by CaulyKan** [electron/electron-api-demos#401]
* What operating system are you using? 
macOS 10.14.1
* What version of Node.js is on your system?
Node.js 10.2.0, Chromium 66.0.3359.181, and Electron 3.0.7.
* How to reproduce
```
$ git clone https://github.com/electron/electron-api-demos
$ cd electron-api-demos
$ npm install
$ npm start
App threw an error during load
ReferenceError: path is not defined
    at Object.<anonymous> (/Users/cauly/Workspace/electron/electron-api-demos/main-process/system/protocol-handler.js:5:77)
    at Object.<anonymous> (/Users/cauly/Workspace/electron/electron-api-demos/main-process/system/protocol-handler.js:15:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at files.forEach (/Users/cauly/Workspace/electron/electron-api-demos/main.js:90:29)
```
* Workaround:
Add `const path = require("path");` to main-process/system/protocol-handler.js

**Comment by balintbalazs** [comment]
I also got the same issue on Windows 10. Same workaround fixed it.
