### ISSUE TITLE
TypeError: app.makeSingleInstance is not a function

### ISSUE THREAD

**Issue by sillyjims** [electron/electron-api-demos#413]
* What operating system are you using? 
MacOS
* What version of Node.js is on your system?
node v10.15.1

npm start

> electron-api-demos@1.5.1 start /Users/jims/Documents/gitproject/electron-api-demos-Zh_CN
> electron .

[11:02:41.359] [info] update-electron-app config looks good; aborting updates since app is in development mode
App threw an error during load
TypeError: app.makeSingleInstance is not a function
    at makeSingleInstance (/Users/jims/Documents/gitproject/electron-api-demos-Zh_CN/main.js:75:14)
    at initialize (/Users/jims/Documents/gitproject/electron-api-demos-Zh_CN/main.js:16:22)
    at Object.<anonymous> (/Users/jims/Documents/gitproject/electron-api-demos-Zh_CN/main.js:89:1)
    at Object.<anonymous> (/Users/jims/Documents/gitproject/electron-api-demos-Zh_CN/main.js:91:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at loadApplicationPackage (/Users/jims/Documents/gitproject/electron-api-demos-Zh_CN/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:119:12)

**Comment by Piliponful** [comment]
Hay, same issue here. Is anyone cares? Is this project have any support?

**Comment by berrylaw** [comment]
Sorry I give up
Don’t count me thank

「piliponful <notifications@github.com>」在 2019年4月26日 週五，下午10:53 寫道：

**Comment by codebytere** [comment]
hey @Piliponful, I'll address this today.

**Comment by Piliponful** [comment]
Thank you

**Comment by nprz** [comment]
Also might want to note `makeSingletonInstance` was deprecated in electron v4, it's now required that you use `requestSingleInstanceLock` [instead](https://electronjs.org/docs/all#appmakesingleinstance).
