### ISSUE TITLE
Unable to install on windows 10

### ISSUE THREAD

**Issue by LouiBelton** [electron/electron-api-demos#453]
I've tried to install these electron demos. Currently im using the corporate laptop for this.

Specs:
Dell Latitude E7470
Using windows 10
npm 6.14.4

Here is the error log

> 18365 verbose stack Error: electron-chromedriver@3.0.0 install: `node ./download-chromedriver.js`
> 18365 verbose stack Exit status 1
> 18365 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
> 18365 verbose stack     at EventEmitter.emit (events.js:310:20)
> 18365 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 18365 verbose stack     at ChildProcess.emit (events.js:310:20)
> 18365 verbose stack     at maybeClose (internal/child_process.js:1021:16)
> 18365 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> 18366 verbose pkgid electron-chromedriver@3.0.0
> 18367 verbose cwd C:\Users\luibel59938\Downloads\electron-api-demos-master\electron-api-demos-master
> 18368 verbose Windows_NT 10.0.15063
> 18369 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
> 18370 verbose node v12.16.3
> 18371 verbose npm  v6.14.4
> 18372 error code ELIFECYCLE
> 18373 error errno 1
> 18374 error electron-chromedriver@3.0.0 install: `node ./download-chromedriver.js`
> 18374 error Exit status 1
> 18375 error Failed at the electron-chromedriver@3.0.0 install script.
> 18375 error This is probably not a problem with npm. There is likely additional logging output above.
> 18376 verbose exit [ 1, true ]

**Comment by PrakharUniyal** [comment]
Hi @LouiBelton ! I have also encountered this issue while building an electron app. Try deleting the node_modules directory and run npm install to reinstall the packages.
